### ISSUE TITLE
Location Services Disabled; Tell them they need to enable.

### ISSUE THREAD

**Issue by cs09g** [RefugeRestrooms/refugerestrooms#264] opened 2016-06-02 04:00 UTC
os: window 7
web browser: latest chrome

when click search button with no query, refreshing animation starts with no reaction.
at least it should show what do i do, and stop the animation because it does not search anything.

**Comment by Hkly** [comment] 2016-11-11 00:11
What's the expected behavior when searching without a query? The pull request referencing this https://github.com/RefugeRestrooms/refugerestrooms/pull/269 seems to imply that it searches the current location if no query is entered, but when I try that I'm just left spinning.

**Comment by cs09g** [comment] 2016-11-11 01:36
It does show the message that a query should be entered, but spinning icon doesn't stop.

**Comment by Hkly** [comment] 2016-12-01 00:42
Ah so it looks like you have location services blocked or disabled on your browser. When location services is enabled, searching with no query does a search on your current location.

A fix for this would maybe be adding a message letting users know they need to enable location services. And stop the animation spinning too :P

**Comment by cs09g** [comment] 2016-12-01 01:27
@Hkly Right! I guessed so. That fix you just mentioned would be great.

**Comment by DeeDeeG** [comment] 2017-11-03 20:46
I believe this is fixed by #359.

**Closed** 2017-11-03 21:17 UTC
Labels: ready
