### ISSUE TITLE
Users to own a bathroom with the ability to edit them? 

### ISSUE THREAD

**Issue by t-walker** [RefugeRestrooms/refugerestrooms#249] opened 2015-10-18 20:20 UTC
While submitting restrooms, one of the addresses didn't place properly and I couldn't edit them. Would it be worth implementing a login system so users can own a bathroom that they submit and edit at a later time?

**Comment by drdpedroso** [comment] 2016-01-04 11:38
What if we leave it all open? For any user to edit?

**Comment by t-walker** [comment] 2016-01-04 17:43
That works as well. Perhaps suggested edits could go into a queue for admin approval?

**Comment by drdpedroso** [comment] 2016-01-04 17:45
Nice! I'll try to implement that in my free time

**Comment by tkwidmer** [comment] 2016-01-04 17:55
@t-walker @drdpedroso There is already a ticket / PR for this #198

**Comment by tkwidmer** [comment] 2016-01-04 22:30
But its been stagnet for a while

**Comment by t-walker** [comment] 2016-02-16 19:42
I added a bunch of bathrooms and since my university refuses to publish the actual street address of the buildings a lot of them are just pinned to Pullman and I'm not sure how to change that. Perhaps before committing to the db you allow people to see where it is pinned and then drag and drop?

**Comment by tkwidmer** [comment] 2016-03-24 23:47
@t-walker I think that also sounds like a good solution.

**Comment by mi-wood** [comment] 2018-01-30 03:31
closing since this is a dupe of https://github.com/RefugeRestrooms/refugerestrooms/issues/126

**Closed by mi-wood** 2018-01-30 03:31 UTC
